### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by albertyw**
Got a bit annoyed by warnings about outdated versions of ansi_up having security issues.  I took a crack at updating ansi_up (and maybe some other dependencies).  

ansi_up documentation: https://github.com/drudru/ansi_up

~~(I'm on an M1 Mac so I can't run phantomjs for tests so I'm hoping CI will be good enough.  However CI is broken, pending #11)~~

This depends on #12 and #13.

### CODE REVIEW

**Comment by albertyw** [comment]
@mantoni ping?

**Comment by mantoni** [comment]
Hey, sorry for being lazy here. I'm on an M1 Mac too, but I have access to another machine that I can use to confirm the tests still pass later today or tomorrow.

**Comment by albertyw** [comment]
I set up CI in #13 so Github can run tests for us.

**Comment by mantoni** [comment]
📦 Released in `v2.2.1`.

Thank you so much for your patience and setting up CI for the project 🙏 ❤️

**Pull request merged**
